<?php

$title = 'SEARCH A FLIGHT';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form->setAttribute('action', $this->url('flights', array('action' => 'index')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('from'));
echo $this->formRow($form->get('to'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();